# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: configure webpacker
          command: |
            yarn && bundle exec rake webpacker:compile

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: >
          git config --global user.email "github@ericgross.com  " &&
          git config --global user.name "CircleCI Testing" &&
          bundle exec overcommit --sign &&
          bundle exec overcommit --run

      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m


      - run:
          name: Create schema
          environment:
            RAILS_ENV: test
          command: bundle exec rake db:create db:migrate

      - run:
          name: Run RSpec tests
          environment:
            braintree_environment: sandbox
            braintree_merchant_id: abc12345
            braintree_public_key: key12345
            braintree_private_key: privatekey12345
          command: |
            mkdir -p tmp/test_results/rspec
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out tmp/test_results/rspec/results.xml \
                            --format progress \
                            $TEST_FILES

      - store_test_results:
          path: tmp/test_results/

      - store_artifacts:
          path:
            log/

      - store_artifacts:
          path:
            tmp/test_results/

  deploy:
    executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install # Runs the heroku install command, if necessary.
      - heroku/deploy-via-git: # Deploys branch to Heroku via git push.
          only-branch: master

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
