development:
  forest_env_secret: e19f87b5a7544e60cb8933e3d1fb3d830288d91f6c397294a6bf836f8c97ae94
  forest_auth_secret: 0Y-Zy43Q_gfnnn9L9Cx80g
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
